POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}


###

GET http://localhost:8080/api/payments/cf14f67c-61c5-4518-ab02-65016003ff96
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/started?pageNumer=0
Accept: application/json
Content-Type: application/json
