POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsImlzcyI6InNob3AiLCJleHAiOjE2OTY1MTc5NzEsInVzZXIiOiJqYW4ifQ.YTSkXTLwq73ITct5UegKX1O0DRe5j_hiD2QjmP4rxQY

{
  "requestId": 1,
  "value": "200 PLN"
}


###

GET http://localhost:8080/api/payments/cf14f67c-61c5-4518-ab02-65016053ff96
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/started?pageNumer=0
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8080/api/tokens
Accept: application/json
Content-Type: application/json

{
  "login": "jan",
  "password": "123"
}
