spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:h2:file:./data/h2.db
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
