spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/payments
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
  #    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
  messages:
    basename: text, exceptions
  data:
    mongodb:
      #uri: mongodb://admin:admin@localhost:27017/payments?authSource=admin&authMechanism=SCRAM-SHA-256
      username: admin
      password: admin
      host: localhost
      port: 27017
      authentication-database: admin
      database: payments
      auto-index-creation: true
logging:
  level:
    org.javamoney.moneta: OFF
server:
  servlet:
    session:
      timeout: 3600s
      cookie:
        max-age: 3600s
