spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/shop
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
  #  jpa:
#    hibernate:
#      ddl-auto: create-drop
  messages:
    basename: text, exceptions
  profiles:
    active: dev
logging:
  level:
    org.javamoney.moneta: OFF
